extract = 'total_dyn_inst: (\d+)'
benchmarks = '../core/*.bril'

[runs.baseline]
pipeline = [
  "bril2json", 
  "brili -p {args}",
]


[runs.trace_correctness]
pipeline = [
  "python ../trace.py -std", 
  "python ../lvn.py",
  "python ../dce.py",
  "brili -p {args}",
]
